URL_BASE_PATH = 'app'
FILES_FOLDER = 'files'

OS_FILES_RELATIVE_BASE_PATH = 'files'
OS_STATIC_RELATIVE_BASE_PATH = 'static'
NETWORK_FILES_RELATIVE_BASE_PATH = 'file'
NETWORK_STATIC_RELATIVE_BASE_PATH = 'static'
